# HX711 calibration

env = Environment(CC='g++', CCFLAGS='-static-libgcc -static-libstdc++')
libs = ['wiringPi',
        'crypt']

src = ['hx711.cpp',
       'hx711.h',
       'main.cpp']

env.Program('calibrate', src, LIBPATH=['/usr/lib',
                                       '/usr/local/lib'])
